### PR TITLE
Dignified pipeline support

### PR DESCRIPTION
**Pull request by JGAntunes**
I noticed the `compliance` tests aren't being executed by the CI nor they're in the pre-commit hooks. Is this by design? If you want I can add it.

### CODE REVIEW

**Comment by diasdavid** [comment]
Thank you for the PR @JGAntunes :) 

I haven't added compliance to CI, because those tests consume a ton of time which makes it a bad UX for dev. Nevertheless it is important to check them always before PR or release.

Could you rebase this branch on latest master?

**Comment by JGAntunes** [comment]
Ok, thanks for clearing that out @diasdavid.

I'll keep an eye on diasdavid/js-libp2p-websockets#8 to see how to organize the browser/node-tests here and work on the rebase meanwhile.

**Comment by diasdavid** [comment]
@JGAntunes the trick is to update the npm scripts to use gulp directly https://github.com/diasdavid/js-libp2p-websockets/blob/master/package.json#L8-L15 . Another great example is: https://github.com/diasdavid/js-libp2p-swarm/blob/master/gulpfile.js

**Comment by JGAntunes** [comment]
@diasdavid I think this is it, let me know if anything is missing ;)

**Comment by diasdavid** [comment]
wooo :D LGTM :) thank you @JGAntunes

**Pull request merged**
